my_turtle:
  background_b: 255
  background_g: 86
  background_r: 150
rosdistro: 'noetic

  '
roslaunch:
  uris:
    host_ubuntu_virtualbox__39745: http://ubuntu-VirtualBox:39745/
rosversion: '1.15.15

  '
run_id: febd2fce-b933-11ed-abf6-45ca9d3823ea
turtle1:
  background_r: 150
turtlesim:
  background_b: 255
  background_g: 86
  background_r: 150
